name: Build

on:
  workflow_run:
    workflows: ["E2E Test"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            dist
            .astro
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.{js,ts,astro,mjs}') }}
          restore-keys: |
            ${{ runner.os }}-build-
      
      - name: Install dependencies
        run: npm ci --omit=optional
      
      - name: Build Astro project
        run: npm run build 