name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install state
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      # ---------- UNIT TESTS ----------
      - name: Run unit tests
        run: npm run test
        env:
          CI: true

      # ---------- E2E SETUP ----------
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ---------- E2E TESTS ----------
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          CI: true