name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Check Vercel secrets
        id: check-secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_ORG_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "secrets_available=false" >> $GITHUB_OUTPUT
            echo "⚠️  Vercel secrets are not configured. Skipping deployment."
            echo ""
            echo "To enable automatic deployments, please add the following secrets to your repository:"
            echo "1. Go to your repository Settings > Secrets and variables > Actions"
            echo "2. Add the following repository secrets:"
            echo "   - VERCEL_TOKEN: Your Vercel API token"
            echo "   - VERCEL_ORG_ID: Your Vercel organization ID"
            echo "   - VERCEL_PROJECT_ID: Your Vercel project ID"
            echo ""
            echo "You can find these values in your Vercel dashboard:"
            echo "- Token: https://vercel.com/account/tokens"
            echo "- Org ID & Project ID: https://vercel.com/dashboard"
          else
            echo "secrets_available=true" >> $GITHUB_OUTPUT
            echo "✅ Vercel secrets are configured. Proceeding with deployment."
          fi
      - name: Deploy to Vercel
        if: steps.check-secrets.outputs.secrets_available == 'true'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod' 