name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Run unit tests
      run: npm test
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run e2e tests
      run: npm run test:e2e
      env:
        CI: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Build project
      run: npm run build
    
    - name: Check Vercel secrets
      id: check-secrets
      run: |
        if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_ORG_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
          echo "secrets_available=false" >> $GITHUB_OUTPUT
          echo "⚠️  Vercel secrets are not configured. Skipping deployment."
          echo ""
          echo "To enable automatic deployments, please add the following secrets to your repository:"
          echo "1. Go to your repository Settings > Secrets and variables > Actions"
          echo "2. Add the following repository secrets:"
          echo "   - VERCEL_TOKEN: Your Vercel API token"
          echo "   - VERCEL_ORG_ID: Your Vercel organization ID"
          echo "   - VERCEL_PROJECT_ID: Your Vercel project ID"
          echo ""
          echo "You can find these values in your Vercel dashboard:"
          echo "- Token: https://vercel.com/account/tokens"
          echo "- Org ID & Project ID: https://vercel.com/dashboard"
        else
          echo "secrets_available=true" >> $GITHUB_OUTPUT
          echo "✅ Vercel secrets are configured. Proceeding with deployment."
        fi
    
    - name: Deploy to Vercel
      if: steps.check-secrets.outputs.secrets_available == 'true'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod' 