name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: [ main ]

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Debug - Check if secrets are available
        run: |
          echo "VERCEL_ORG_ID exists: ${{ secrets.VERCEL_ORG_ID != '' }}"
          echo "VERCEL_PROJECT_ID exists: ${{ secrets.VERCEL_PROJECT_ID != '' }}"
          echo "VERCEL_TOKEN exists: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "VERCEL_TOKEN length: ${{ secrets.VERCEL_TOKEN != '' && length(secrets.VERCEL_TOKEN) || '0' }}"
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="${{ secrets.VERCEL_TOKEN }}"
        
      - name: Build Project Artifacts
        run: vercel build --token="${{ secrets.VERCEL_TOKEN }}"
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="${{ secrets.VERCEL_TOKEN }}" 