name: Security Scan

on:
  schedule:
    # Ejecutar semanalmente los domingos a las 2 AM UTC
    - cron: '0 2 * * 0'
  pull_request:
    branches: [ main ]

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        
      - name: Run npm outdated check
        run: npm outdated || true
        
      - name: Check for known vulnerabilities
        run: |
          echo "Checking for known vulnerabilities..."
          npm audit --json > audit-report.json || true
          if [ -s audit-report.json ]; then
            echo "Vulnerabilities found:"
            cat audit-report.json | jq '.metadata.vulnerabilities' || echo "No vulnerabilities found"
          else
            echo "No vulnerabilities detected"
          fi 